### ISSUE TITLE
Dots and commas not working

### ISSUE THREAD

**Issue by Hojott** [JohkuF/Amdahl-s-law-visualisation#1]
Writing a dot or a comma in the calculator clears the textbox

**Comment by Hojott** [comment]
I use Debian Bookworm and have Firefox ESR.

**Comment by JohkuF** [comment]
The issue reported by @Hojott appears to be specific to the user's local environment or configuration. As other users have not experienced the same problem, we believe this is an isolated issue and recommend @Hojott to check their browser settings, clear their cache, or try accessing the application from a different device or network. Given that this issue does not affect the general user base, we will close it. If @Hojott continues to experience the problem, they are encouraged to reach out for individual support.

**Comment by Hojott** [comment]
Can I have invidual support?

**Comment by Hojott** [comment]
I have tried clearing my cache and disabling my adblock and tracking protection, as well as using a different device without avail. :(

**Comment by JohkuF** [comment]
Okay, I fixed it :)
